language: java
jdk: oraclejdk11
addons:
  sonarcloud:
    organization: kryffin
    token:
      secure: llnIEWLUg+tfM5kqRUkCjFc+NoKp30SCS6d9AoQ3XUrhutrgzZHnPD/zuDH+AeNyaDBmOwumWpqEJFxcF3wayeUOBQvktOohTKh2QPyRYyZrhxjmjkTJNCAGgQrW8Jdf74RWai4GBw9JlaCWAQg2AS5/NbAbshjcfK7UjXplzG1Pp62ryYe5/YYrP/OoNSkYsypRmBz03m9pa5J1Wc0Fe9MiqEYmW/OpWOOyprsKcUyJ8WJQzxaArl55ziRSsVSUztQyHTRnMIkDXgRxKFQ5gpf1C1BV3p95+FSQOGSMri0d7ZU/PjHHg4Wu0lcNybob2tEdc6fnsg7UTgRWmZAWqcCoD1yanf8iXN6izbk0S6SJrJeDXacuOdZr90TDK/jq0O926N2gSs58fd7joGyCTyCRLCqj4lHsQvAQo/wYxc3VxMfSZEx+tWnTmvryLLaXNyOsStwVbVlpj4tW2dG+/VWnXe8lWTGc76alK10oyy0gB5A/YXUjmSJ9zUadZ19thFeD+zeo/ZHlPkCDEchDkExXuMi1NPZvrHRWE52vdf5aG4cVgPLA06yyA2iaVK3WX5b0614sEy73YChpFjBlHd7ZSdDIFSGakThML4FZK0ngucATgKSjfYhU3wxDyy8R4my/RIAQYeHiBObgtvyOxK8WNMpKV7cpmG4Wmte8UPw=
script:
- mvn clean verify
after_deploy:
- echo "done deploying"
env:
  global:
  - secure: llnIEWLUg+tfM5kqRUkCjFc+NoKp30SCS6d9AoQ3XUrhutrgzZHnPD/zuDH+AeNyaDBmOwumWpqEJFxcF3wayeUOBQvktOohTKh2QPyRYyZrhxjmjkTJNCAGgQrW8Jdf74RWai4GBw9JlaCWAQg2AS5/NbAbshjcfK7UjXplzG1Pp62ryYe5/YYrP/OoNSkYsypRmBz03m9pa5J1Wc0Fe9MiqEYmW/OpWOOyprsKcUyJ8WJQzxaArl55ziRSsVSUztQyHTRnMIkDXgRxKFQ5gpf1C1BV3p95+FSQOGSMri0d7ZU/PjHHg4Wu0lcNybob2tEdc6fnsg7UTgRWmZAWqcCoD1yanf8iXN6izbk0S6SJrJeDXacuOdZr90TDK/jq0O926N2gSs58fd7joGyCTyCRLCqj4lHsQvAQo/wYxc3VxMfSZEx+tWnTmvryLLaXNyOsStwVbVlpj4tW2dG+/VWnXe8lWTGc76alK10oyy0gB5A/YXUjmSJ9zUadZ19thFeD+zeo/ZHlPkCDEchDkExXuMi1NPZvrHRWE52vdf5aG4cVgPLA06yyA2iaVK3WX5b0614sEy73YChpFjBlHd7ZSdDIFSGakThML4FZK0ngucATgKSjfYhU3wxDyy8R4my/RIAQYeHiBObgtvyOxK8WNMpKV7cpmG4Wmte8UPw=
